# 站点基本信息
site_name: Soresen's Quant Knowledge Pages  # 改成你的博客名称
site_description: Something I learned in Quant  # 站点描述
site_author: AkemiHikari  # 你的名字
site_url: https://your-domain.com  # 你的站点URL，部署后更新

# 主题配置
theme:
  name: material  # 使用material主题
  language: zh  # 设置为中文（部分UI元素会汉化）[8](@ref)
  palette:
    # 配色方案（默认提供 light 和 dark 模式）
    - scheme: default
      toggle:
        icon: material/weather-sunny  # 亮模式图标
        name: 切换到深色模式
    - scheme: slate
      toggle:
        icon: material/weather-night  # 暗模式图标
        name: 切换到浅色模式
  features:
    - navigation.tabs  # 导航选项卡
    - navigation.path  # 显示当前页面路径
    - search.suggest  # 搜索建议
    - search.highlight  # 搜索关键词高亮
    - content.code.copy  # 代码块复制按钮
    - content.code.annotate  # 
    - navigation.top  # 返回顶部按钮

# 导航菜单
nav:
  - 首页: index.md
  - 基础知识:
    - 概述: base/base.md
    - 数学基础: base/math.md
    - 统计基础: base/stat.md
    - 机器学习基础: base/ml.md
    - 金融基础: base/finance.md
  - 特征&因子: feature&alpha/alpha_search.md
  - 模型: model/model.md
  - 策略: 
    - 概述: strategy/strategy.md
    - Barra Model - Soresen Wanyan internship: strategy/barra.md
  - 交易执行: 
    - 概述: execution/execution.md
    - Hawkes Model - Soresen Longqi internship: execution/hawkes.md

# 插件
plugins:
  - search  # 内置搜索插件

# 扩展 Markdown 语法支持（按需启用）
markdown_extensions:
  - admonition  # 提示框
  - pymdownx.details  # 折叠块
  - pymdownx.superfences  # 更强大的代码块
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  
  - pymdownx.arithmatex:  # 这个扩展负责处理公式
      generic: true       # 建议设置为 true，以获得更好的兼容性

extra_javascript:
  - docs/javascripts/mathjax.js  # 先加载自定义配置
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js  # 加载 MathJax

# 版权信息
copyright: Copyright &copy; 2025 AkemiHikari  # 你的版权信息